In [52]:
import pandas as pd

In [51]:
alaska = 'nps_df.csv'
alaska_df = pd.read_csv(alaska)

In [53]:
alaska_df.head(52)

,park_code,national_park,state,acres,latitude,longitude
0,ACAD,Acadia National Park,Maine,47390,44.35,-68.21
1,ARCH,Arches National Park,Utah,76519,38.68,-109.57
2,BADL,Badlands National Park,South Dakota,242756,43.75,-102.50
3,BIBE,Big Bend National Park,Texas,801163,29.25,-103.25
4,BISC,Biscayne National Park,Florida,172924,25.65,-80.08
5,BLCA,Black Canyon of the Gunnison National Park,Colorado,32950,38.57,-107.72
6,BRCA,Bryce Canyon National Park,Utah,35835,37.57,-112.18
7,CANY,Canyonlands National Park,Utah,337598,38.20,-109.93
8,CARE,Capitol Reef National Park,Utah,241904,38.20,-111.17
9,CAVE,Carlsbad Caverns National Park,New Mexico,46766,32.17,-104.44
10,CHIS,Channel Islands National Park,California,249561,34.01,-119.42
11,CONG,Congaree National Park,South Carolina,26546,33.78,-80.78
12,CRLA,Crater Lake National Park,Oregon,183224,42.94,-122.10
13,CUVA,Cuyahoga Valley National Park,Ohio,32950,41.24,-81.55
14,DENA,Denali National Park,Alaska,3372402,63.33,-150.50
15,DEVA,Death Valley National Park,"CA, NV",4740912,36.24,-116.82
16,DRTO,Dry Tortugas National Park,Florida,64701,24.63,-82.87
17,EVER,Everglades National Park,Florida,1508538,25.32,-80.93
18,GAAR,Gates of the Arctic National Park,Alaska,7523898,67.78,-153.30
19,GLAC,Glacier National Park,Montana,1013572,48.80,-114.00
20,GLBA,Glacier Bay National Park,Alaska,3224840,58.50,-137.00
21,GRBA,Great Basin National Park,Nevada,77180,38.98,-114.30
22,GRCA,Grand Canyon National Park,Arizona,1217403,36.06,-112.14
23,GRSA,Great Sand Dunes National Park,Colorado,42984,37.73,-105.51
24,GRSM,Great Smoky Mountains National Park,"TN, NC",521490,35.68,-83.53
25,GRTE,Grand Teton National Park,Wyoming,309995,43.73,-110.80
26,GUMO,Guadalupe Mountains National Park,Texas,86416,31.92,-104.87
27,HALE,Haleakala National Park,Hawaii,29094,20.72,-156.17
28,HAVO,Hawaii Volcanoes National Park,Hawaii,323431,19.38,-155.20
29,HOSP,Hot Springs National Park,Arkansas,5550,34.51,-93.05
30,ISRO,Isle Royale National Park,Michigan,571790,48.10,-88.55
31,JOTR,Joshua Tree National Park,California,789745,33.79,-115.90
32,KATM,Katmai National Park,Alaska,3674530,58.50,-155.00
33,KEFJ,Kenai Fjords National Park,Alaska,669983,59.92,-149.65
34,KOVA,Kobuk Valley National Park,Alaska,1750717,67.55,-159.28
35,LACL,Lake Clark National Park,Alaska,2619733,60.97,-153.42
36,LAVO,Lassen Volcanic National Park,California,106372,40.49,-121.51
37,MACA,Mammoth Cave National Park,Kentucky,52830,37.18,-86.10
38,MEVE,Mesa Verde National Park,Colorado,52122,37.18,-108.49
39,MORA,Mount Rainier National Park,Washington,235625,46.85,-121.75
40,NOCA,North Cascades National Park,Washington,504781,48.70,-121.20
41,OLYM,Olympic National Park,Washington,922651,47.97,-123.50
42,PEFO,Petrified Forest National Park,Arizona,93533,35.07,-109.78
43,PINN,Pinnacles National Park,California,26606,36.48,-121.16
44,REDW,Redwood National Park,California,112512,41.30,-124.00
45,ROMO,Rocky Mountain National Park,Colorado,265828,40.40,-105.58
46,SAGU,Saguaro National Park,Arizona,91440,32.25,-110.50
47,SEKI,Sequoia and Kings Canyon National Parks,California,865952,36.43,-118.68
48,SHEN,Shenandoah National Park,Virginia,199045,38.53,-78.35
49,THRO,Theodore Roosevelt National Park,North Dakota,70447,46.97,-103.45
50,VOYA,Voyageurs National Park,Minnesota,218200,48.50,-92.88
51,WICA,Wind Cave National Park,South Dakota,28295,43.57,-103.48

In [48]:
unique_state = alaska_df["park_code"].unique()
unique_state

array(['DENA', 'GAAR', 'GLBA', 'KATM', 'KEFJ', 'KOVA', 'LACL', 'WRST'],
      dtype=object)

In [55]:
alaska_df = alaska_df.loc[alaska_df["state"] == "Alaska", :]
alaska_df.head(7)

,park_code,national_park,state,acres,latitude,longitude
14,DENA,Denali National Park,Alaska,3372402,63.33,-150.50
18,GAAR,Gates of the Arctic National Park,Alaska,7523898,67.78,-153.30
20,GLBA,Glacier Bay National Park,Alaska,3224840,58.50,-137.00
32,KATM,Katmai National Park,Alaska,3674530,58.50,-155.00
33,KEFJ,Kenai Fjords National Park,Alaska,669983,59.92,-149.65
34,KOVA,Kobuk Valley National Park,Alaska,1750717,67.55,-159.28
35,LACL,Lake Clark National Park,Alaska,2619733,60.97,-153.42

In [66]:
national_parks = alaska_df.copy()
del national_parks['acres']
del national_parks['state']
national_parks

   park_code                      national_park  latitude  longitude
14      DENA               Denali National Park     63.33    -150.50
18      GAAR  Gates of the Arctic National Park     67.78    -153.30
20      GLBA          Glacier Bay National Park     58.50    -137.00
32      KATM               Katmai National Park     58.50    -155.00
33      KEFJ         Kenai Fjords National Park     59.92    -149.65
34      KOVA         Kobuk Valley National Park     67.55    -159.28
35      LACL           Lake Clark National Park     60.97    -153.42
52      WRST  Wrangell - St Elias National Park     61.00    -142.00

In [68]:
national_parks.to_csv('Alaska_parks.csv')